import { employees } from './data/employees'

export const config = {
  colors: {
    light: {
      primary: '#f79039',
      primaryHover: '#e07d2d',
      primaryLight: '#fff0e0',
      primaryLighter: '#fffbf5',
      secondary: '#ffffff',
      background: '#faf8f6',
      surface: '#ffffff',
      surfaceHover: '#fffbf5',
      text: '#1e293b',
      textSecondary: '#64748b',
      textMuted: '#94a3b8',
      border: '#e2e8f0',
      borderLight: '#f1f5f9',
      success: '#16a34a',
      successLight: '#dcfce7',
      danger: '#ef4444',
      dangerLight: '#fef2f2',
      warning: '#f59e0b',
      warningLight: '#fffbeb',
      accent: '#e07d2d',
      shadow: 'rgba(0, 0, 0, 0.08)',
      shadowHeavy: 'rgba(0, 0, 0, 0.15)',
      overlay: 'rgba(0, 0, 0, 0.4)',
      gradient1: '#f79039',
      gradient2: '#e07d2d',
      gradient3: '#d06a1f',
    },
    dark: {
      primary: '#ffaa5e',
      primaryHover: '#ffbf80',
      primaryLight: '#3d2510',
      primaryLighter: '#1a1008',
      secondary: '#1e1e2e',
      background: '#0b1120',
      surface: '#141c2e',
      surfaceHover: '#1f2a3e',
      text: '#e2e8f0',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      border: '#2a3548',
      borderLight: '#172236',
      success: '#22c55e',
      successLight: '#14532d',
      danger: '#f87171',
      dangerLight: '#451a1a',
      warning: '#fbbf24',
      warningLight: '#422006',
      accent: '#ffbf80',
      shadow: 'rgba(0, 0, 0, 0.3)',
      shadowHeavy: 'rgba(0, 0, 0, 0.5)',
      overlay: 'rgba(0, 0, 0, 0.6)',
      gradient1: '#ffaa5e',
      gradient2: '#f79039',
      gradient3: '#e07d2d',
    },
  },

  teams: [
    { id: 'sis', name: 'Tim Sistem Informasi Statistik' },
    { id: 'metods', name: 'Tim Metodologi Statistik dan Sains Data' },
  ],

  employees,

  team: {
    name: 'Tim Teknologi Informasi',
    institution: 'BPS Provinsi Sumatera Barat',
    code: '1300',
    leader: 'Aan Subrata',
    fullTitle: 'Laporan Aktivitas Mingguan Tim Teknologi Informasi',
    subtitle: 'BPS Provinsi Sumatera Barat',
  },

  export: {
    headerColor: 'f79039',
    fontFamily: 'Times New Roman',
    fontSize: 11,
    titleFontSize: 14,
  },

  apiUrl: import.meta.env.VITE_API_URL || '',
  geminiApiKey: import.meta.env.VITE_GEMINI_API_KEY || '',
}
